name: Tests

on:
  push:
    branches:
      - ''
  pull_request:
    branches:
      - ''

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if the repository is private
        run: |
          if [ "${{ github.event.repository.private }}" != "true" ]; then
            echo "❌ Repository must be private"
            exit 1
          fi

      - name: Tests
        uses: Yandex-Practicum/test-project-action@v1
        with:
          project: 'ono-tebe-nado-fd'
